FROM node:20-alpine

WORKDIR /app

# Instala dependencias
COPY package*.json ./
RUN npm install

# Copia el código fuente
COPY . .

# Expone el puerto
EXPOSE 3000

# Ejecuta en modo desarrollo (hot reload con nodemon)
CMD ["npm", "run", "start:dev"]
